version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - cache:/data
  scraper:
    image: engadget-scraper
    build:
      context: ./
    depends_on:
      - cache
    links:
      - cache
volumes:
  cache:
    driver: local